# Generated by Django 2.1.1 on 2018-10-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekmovanja', '0002_auto_20181010_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='potrjen',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
