# Generated by Django 2.1.1 on 2018-10-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tekmovanja', '0004_potrditve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potrditve',
            old_name='ID_Potrditelj',
            new_name='Potrditelj',
        ),
        migrations.RenameField(
            model_name='potrditve',
            old_name='ID_Zahteva',
            new_name='Zahteva',
        ),
    ]
